<a href="https://colab.research.google.com/github/nurrizkyimani/nlp-clickbait-transfers/blob/main/AUGUST_DONE_project_transfer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Drive 

In [1]:
from google.colab import drive
drive.mount("/content/drive/")

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


# DRAFT 1


## Import 

In [ ]:
#!pip install pytorch-nlp
import pandas as pd
import numpy as np

## Preprocessing 

In [ ]:
path = "/content/drive/MyDrive/nlp_research/2022_thesis_styletransfer/annotated/combined/csv/"

all_agree_path = path + "all_agree.csv"

In [ ]:
all_agree_pd = pd.read_csv(all_agree_path)

In [ ]:
all_agree_pd.head()

title          label  \
0  Masuk Radar Pilwalkot Medan, Menantu Jokowi Be...  non-clickbait   
1  Malaysia Sudutkan RI: Isu Kabut Asap hingga In...  non-clickbait   
2  Viral! Driver Ojol di Bekasi Antar Pesanan Mak...      clickbait   
3  Kemensos Salurkan Rp 7,3 M bagi Korban Kerusuh...  non-clickbait   
4  MPR: Amandemen UUD 1945 Tak Akan Melebar ke Ma...  non-clickbait   

   label_score  
0            0  
1            0  
2            1  
3            0  
4            0

In [ ]:
all_agree_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8613 entries, 0 to 8612
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   title        8613 non-null   object
 1   label        8613 non-null   object
 2   label_score  8613 non-null   int64 
dtypes: int64(1), object(2)
memory usage: 202.0+ KB


In [ ]:
all_agree_pd['label'].value_counts()

non-clickbait    5297
clickbait        3316
Name: label, dtype: int64

In [ ]:
df_clickbait = all_agree_pd[all_agree_pd['label'] == "clickbait"]
df_nonclickbait = all_agree_pd[all_agree_pd['label'] == "non-clickbait"]

In [ ]:
df_clickbait.head()

title      label  label_score
2   Viral! Driver Ojol di Bekasi Antar Pesanan Mak...  clickbait            1
8   Ada Motor Nyangkut di Atas Bambu di Sleman, Ko...  clickbait            1
10       Pesan Gamblang Poyuono Menolak Revisi UU KPK  clickbait            1
30  Kocak! Maling di Rumah Mewah Jakut Terekam CCT...  clickbait            1
37  Viral Video Diduga Baku Tembak di Sleman, Ini ...  clickbait            1

In [ ]:
df_nonclickbait.head()

title          label  \
0  Masuk Radar Pilwalkot Medan, Menantu Jokowi Be...  non-clickbait   
1  Malaysia Sudutkan RI: Isu Kabut Asap hingga In...  non-clickbait   
3  Kemensos Salurkan Rp 7,3 M bagi Korban Kerusuh...  non-clickbait   
4  MPR: Amandemen UUD 1945 Tak Akan Melebar ke Ma...  non-clickbait   
5  Peringati Tahun Baru Islam, Banyuwangi Kembali...  non-clickbait   

   label_score  
0            0  
1            0  
3            0  
4            0  
5            0

In [ ]:
#creating a concatination of both df clickbait and nonclickbait
df_both = pd.concat((df_clickbait, df_nonclickbait), ignore_index=True)
df_both.head(-2)

title          label  \
0     Viral! Driver Ojol di Bekasi Antar Pesanan Mak...      clickbait   
1     Ada Motor Nyangkut di Atas Bambu di Sleman, Ko...      clickbait   
2          Pesan Gamblang Poyuono Menolak Revisi UU KPK      clickbait   
3     Kocak! Maling di Rumah Mewah Jakut Terekam CCT...      clickbait   
4     Viral Video Diduga Baku Tembak di Sleman, Ini ...      clickbait   
...                                                 ...            ...   
8606  KPK Tepis Tudingan Moeldoko Soal Hambat Investasi  non-clickbait   
8607  Smart SIM Diluncurkan, Wakapolri Harap Bisa Me...  non-clickbait   
8608  Wamena Papua Kembali Membara, Kantor Bupati Di...  non-clickbait   
8609         BMKG Angkat Bicara Soal Langit Merah Jambi  non-clickbait   
8610  Operasional Bandara Wamena Dihentikan Akibat R...  non-clickbait   

      label_score  
0               1  
1               1  
2               1  
3               1  
4               1  
...           ...  
8606            0  
8607            0  
8608            0  
8609            0  
8610            0  

[8611 rows x 3 columns]

In [ ]:
df_both['data_label'] = np.where(df_both['label'] == "clickbait", 1, 0)

In [ ]:
df_both_clean = df_both.drop('label_score', axis=1)
df_both_clean['data_label'] = df_both_clean["data_label"].astype(float)

In [ ]:
df_both_clean = df_both_clean.drop('label', axis=1)

In [ ]:
d_all = df_both_clean

In [ ]:
d_all.columns = ['text', 'labels']

In [ ]:
cols = d_all.columns.tolist()
cols = cols[-1:] + cols[:-1]
d_all = d_all[cols]

In [ ]:
# df for clickbait turn into d_neg
df_clickbait['data_label'] = np.where(df_clickbait['label'] == "clickbait", 1, 0)
df_click_clean = df_clickbait.drop('label_score', axis=1)
df_click_clean['data_label'] = df_click_clean["data_label"].astype(float)
df_click_clean = df_click_clean.drop('label', axis=1)

d_pos = df_click_clean
d_pos.columns = ['text', 'labels']
d_c = d_pos

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
d_pos.head()

text  labels
2   Viral! Driver Ojol di Bekasi Antar Pesanan Mak...     1.0
8   Ada Motor Nyangkut di Atas Bambu di Sleman, Ko...     1.0
10       Pesan Gamblang Poyuono Menolak Revisi UU KPK     1.0
30  Kocak! Maling di Rumah Mewah Jakut Terekam CCT...     1.0
37  Viral Video Diduga Baku Tembak di Sleman, Ini ...     1.0

In [ ]:
df_nonclickbait['data_label'] = np.where(df_nonclickbait['label'] == "non-clickbait", 0, 1)
df_nonclick_clean = df_nonclickbait.drop('label_score', axis=1)
df_nonclick_clean['data_label'] = df_nonclick_clean["data_label"].astype(float)
df_nonclick_clean = df_nonclick_clean.drop('label', axis=1)

d_neg = df_nonclick_clean
d_neg.columns = ['text', 'labels']
d_nc = d_neg

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
d_pos = d_c
d_neg = d_nc
d_both = d_all

In [ ]:
d_both=d_both.iloc[:,0]

In [ ]:
d_both

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ... 
8608    0.0
8609    0.0
8610    0.0
8611    0.0
8612    0.0
Name: labels, Length: 8613, dtype: float64

In [ ]:
d_pos=d_pos.iloc[:,0]
d_neg=d_neg.iloc[:,0]

## EDA

In [ ]:
bag_of_word = pd.Series([y for x in d_all['title'].values.flatten() for y in x.split()]).value_counts()

KeyError: ignored

In [ ]:
bag_of_word[50:100]

In [ ]:
d_both = d_all
d_pos = df_clickbait
d_neg = df_nonclickbait

d_pos=d_pos.iloc[:,0]
d_neg=d_neg.iloc[:,0]
d_both=d_both.iloc[:,0]

## Retrieve

## Delete 

In [ ]:
def get_attribute():


def create_ngram():



# NEW DRAFT STYLE TRANSFER


## Per-Install-an

In [2]:
!pip install fse

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 90 kB 5.1 MB/s 
     |████████████████████████████████| 24.1 MB 90.2 MB/s 
     |████████████████████████████████| 56.8 MB 1.2 MB/s 
     |████████████████████████████████| 101 kB 12.3 MB/s 
     |████████████████████████████████| 53 kB 1.6 MB/s 
     |████████████████████████████████| 596 kB 57.1 MB/s 
  Created wheel for fse: filename=fse-1.0.0-cp37-cp37m-linux_x86_64.whl size=235679 sha256=a7922f55d1ee5ebd96e9c1d7d7bde228bb4da5dfa785c78db9054d7edbfee158
  Stored in directory: /root/.cache/pip/wheels/d5/65/7e/900c293350aa3b6bcaefcd66ec5757d43206b610a467093993
Successfully built fse
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
  Attempting uninstall: gensim
    Found existing installation: gensim 3.6.0
    Uninstalling gensim-3.6.0:
      Success

In [3]:
!pip install pytorch-nlp

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 90 kB 3.8 MB/s 


In [4]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os

import re
import string 
import collections
import fse
import random

import torch
import torch.nn as nn
from torch import optim
import torch.nn.functional as F
from torchnlp.metrics import get_moses_multi_bleu

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.manual_seed(1)

import nltk
nltk.download('punkt')

# Any results you write to the current directory are saved as output.

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [5]:
#!pip install pytorch-nlp
import pandas as pd
import numpy as np

## DATA PREPROCESS

In [6]:
path = "/content/drive/MyDrive/nlp_research/2022_thesis_styletransfer/annotated/combined/csv/"

all_agree_path = path + "all_agree.csv"

In [7]:
all_agree_pd = pd.read_csv(all_agree_path)

In [8]:
all_agree_pd.head()

title          label  \
0  Masuk Radar Pilwalkot Medan, Menantu Jokowi Be...  non-clickbait   
1  Malaysia Sudutkan RI: Isu Kabut Asap hingga In...  non-clickbait   
2  Viral! Driver Ojol di Bekasi Antar Pesanan Mak...      clickbait   
3  Kemensos Salurkan Rp 7,3 M bagi Korban Kerusuh...  non-clickbait   
4  MPR: Amandemen UUD 1945 Tak Akan Melebar ke Ma...  non-clickbait   

   label_score  
0            0  
1            0  
2            1  
3            0  
4            0

In [9]:
df_clickbait = all_agree_pd[all_agree_pd['label'] == "clickbait"]
df_nonclickbait = all_agree_pd[all_agree_pd['label'] == "non-clickbait"]

In [10]:
#creating a concatination of both df clickbait and nonclickbait
df_both = pd.concat((df_clickbait, df_nonclickbait), ignore_index=True)
df_both.head(-2)

title          label  \
0     Viral! Driver Ojol di Bekasi Antar Pesanan Mak...      clickbait   
1     Ada Motor Nyangkut di Atas Bambu di Sleman, Ko...      clickbait   
2          Pesan Gamblang Poyuono Menolak Revisi UU KPK      clickbait   
3     Kocak! Maling di Rumah Mewah Jakut Terekam CCT...      clickbait   
4     Viral Video Diduga Baku Tembak di Sleman, Ini ...      clickbait   
...                                                 ...            ...   
8606  KPK Tepis Tudingan Moeldoko Soal Hambat Investasi  non-clickbait   
8607  Smart SIM Diluncurkan, Wakapolri Harap Bisa Me...  non-clickbait   
8608  Wamena Papua Kembali Membara, Kantor Bupati Di...  non-clickbait   
8609         BMKG Angkat Bicara Soal Langit Merah Jambi  non-clickbait   
8610  Operasional Bandara Wamena Dihentikan Akibat R...  non-clickbait   

      label_score  
0               1  
1               1  
2               1  
3               1  
4               1  
...           ...  
8606            0  
8607            0  
8608            0  
8609            0  
8610            0  

[8611 rows x 3 columns]

In [11]:
df_both_l = df_both.copy()

df_both_l['label'] = df_both_l['label'].astype('category')

In [12]:
df_both_l.head(-1)

title          label  \
0     Viral! Driver Ojol di Bekasi Antar Pesanan Mak...      clickbait   
1     Ada Motor Nyangkut di Atas Bambu di Sleman, Ko...      clickbait   
2          Pesan Gamblang Poyuono Menolak Revisi UU KPK      clickbait   
3     Kocak! Maling di Rumah Mewah Jakut Terekam CCT...      clickbait   
4     Viral Video Diduga Baku Tembak di Sleman, Ini ...      clickbait   
...                                                 ...            ...   
8607  Smart SIM Diluncurkan, Wakapolri Harap Bisa Me...  non-clickbait   
8608  Wamena Papua Kembali Membara, Kantor Bupati Di...  non-clickbait   
8609         BMKG Angkat Bicara Soal Langit Merah Jambi  non-clickbait   
8610  Operasional Bandara Wamena Dihentikan Akibat R...  non-clickbait   
8611   Asap Karhutla Riau Mulai Merambah Ke Nias, BM...  non-clickbait   

      label_score  
0               1  
1               1  
2               1  
3               1  
4               1  
...           ...  
8607            0  
8608            0  
8609            0  
8610            0  
8611            0  

[8612 rows x 3 columns]

In [13]:
df_both_label = df_both_l.drop('label_score', axis=1)
df_both = df_both_l.drop('label', axis=1)

In [14]:
df_both.head(-5)

title  label_score
0     Viral! Driver Ojol di Bekasi Antar Pesanan Mak...            1
1     Ada Motor Nyangkut di Atas Bambu di Sleman, Ko...            1
2          Pesan Gamblang Poyuono Menolak Revisi UU KPK            1
3     Kocak! Maling di Rumah Mewah Jakut Terekam CCT...            1
4     Viral Video Diduga Baku Tembak di Sleman, Ini ...            1
...                                                 ...          ...
8603  Komnas HAM Minta Aparat Keamanan Tak Gunakan K...            0
8604  Mahasiswa Minta TNI Turun Bersama Kawal Aksi D...            0
8605  Polisi Pulangkan 56 Mahasiswa Setelah Sempat D...            0
8606  KPK Tepis Tudingan Moeldoko Soal Hambat Investasi            0
8607  Smart SIM Diluncurkan, Wakapolri Harap Bisa Me...            0

[8608 rows x 2 columns]

In [15]:
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()

df_both_l['label_encoding'] = labelencoder.fit_transform(df_both_l['label'])



In [16]:
df_both_l.head()

title      label  label_score  \
0  Viral! Driver Ojol di Bekasi Antar Pesanan Mak...  clickbait            1   
1  Ada Motor Nyangkut di Atas Bambu di Sleman, Ko...  clickbait            1   
2       Pesan Gamblang Poyuono Menolak Revisi UU KPK  clickbait            1   
3  Kocak! Maling di Rumah Mewah Jakut Terekam CCT...  clickbait            1   
4  Viral Video Diduga Baku Tembak di Sleman, Ini ...  clickbait            1   

   label_encoding  
0               0  
1               0  
2               0  
3               0  
4               0

In [17]:
df_encode_clean = df_both_l.copy()

df_encode_clean = df_both = df_both_l.drop(['label_score'], axis=1)

In [18]:
df_encode_clean.head()

title      label  \
0  Viral! Driver Ojol di Bekasi Antar Pesanan Mak...  clickbait   
1  Ada Motor Nyangkut di Atas Bambu di Sleman, Ko...  clickbait   
2       Pesan Gamblang Poyuono Menolak Revisi UU KPK  clickbait   
3  Kocak! Maling di Rumah Mewah Jakut Terekam CCT...  clickbait   
4  Viral Video Diduga Baku Tembak di Sleman, Ini ...  clickbait   

   label_encoding  
0               0  
1               0  
2               0  
3               0  
4               0

In [19]:
df_clickbait_c = df_encode_clean[df_encode_clean['label'] == "clickbait"]
df_nonclickbait_c = df_encode_clean[df_encode_clean['label'] == "non-clickbait"]

In [20]:
df_clickbait_t = df_clickbait_c.drop(['label', 'label_encoding'], axis=1)

In [21]:
ldsdf = df_clickbait_t.values.tolist()

In [22]:
ldsdf[0][0]

'Viral! Driver Ojol di Bekasi Antar Pesanan Makanan Pakai Sepeda'

In [23]:
import itertools

df_clickbait_t = df_clickbait_c.drop(['label', 'label_encoding'], axis=1)
clickbait_l = df_clickbait_t.values.tolist()
clickbait_l_c = list(itertools.chain.from_iterable(clickbait_l))

df_nonclickbait_t = df_nonclickbait_c.drop(['label', 'label_encoding'], axis=1)
nonclickbait_l = df_nonclickbait_t.values.tolist()
nonclickbait_l_c = list(itertools.chain.from_iterable(nonclickbait_l))

## DELETE FUNC

### Real Delete

In [24]:
#Parameters:
param_smooth = 1
param_span = 3

param_backoff_limit = 3

max_length = param_span
min_length = 1

#ngram has punctuation
def has_punctuation(ngram): #damn I'm very proud of making this from scratch lol, looks elegant in one line
    return True in [x in string.punctuation for x in ngram]

def generate_ngrams(lines, min_length=1, max_length=param_span):
#     lines = placeholder + lines
    lengths = range(min_length, max_length + 1)
    ngrams = {length: [] for length in lengths}
    queue = collections.deque(maxlen=max_length)
    
    def add_queue():
        current = tuple(queue)
        for length in lengths:
            if len(current) >= length and not has_punctuation(current[:length]):
                ngrams[length].append(current[:length])
    
    short_by = 0
    for line in lines:
        short_by = max(0, max_length - len(lines))
        for word in line.split():
            queue.append(word)
            if len(queue) >= max_length-short_by:
                add_queue()                

    while len(queue) > min_length:
        queue.popleft()
        add_queue()
    return ngrams

#modified from & fixed their error of ngram with # of words < 4: https://gist.github.com/benhoyt/dfafeab26d7c02a52ed17b6229f0cb52
def count_ngrams(lines, min_length=1, max_length=param_span):
    """Iterate through given lines iterator (file object or list of
    lines) and return n-gram frequencies. The return value is a dict
    mapping the length of the n-gram to a collections.Counter
    object of n-gram tuple and number of times that n-gram occurred.
    Returned dict includes n-grams of length min_length to max_length.
    """
    lengths = range(min_length, max_length + 1)
    ngrams = {length: collections.Counter() for length in lengths}
    queue = collections.deque(maxlen=max_length)

    # Helper function to add n-grams at start of current queue to dict
    def add_queue():
        current = tuple(queue)
        for length in lengths:
            if len(current) >= length and not has_punctuation(current[:length]):
                ngrams[length][current[:length]] += 1

    # Loop through all lines and words and add n-grams to dict
    short_by = 0
    for line in lines:
        short_by = max(0, max_length - len(lines))
        for word in line.split():
            queue.append(word)
            if len(queue) >= max_length - short_by:
                add_queue()

    # Make sure we get the n-grams at the tail end of the queue
    while len(queue) > min_length:
        queue.popleft()
        add_queue()

    return ngrams

In [25]:
# call the generate n-grams; 
test_nonclicbait = generate_ngrams(nonclickbait_l_c)
# get the type of the result of n-grma which is tuple
type(test_nonclicbait[1][1])
# res: tuple 

# call the generate n-grams; 
test_clickbait = count_ngrams(clickbait_l_c)
# get the type of the result of n-grma which is tuple
type(test_clickbait[1][1])
# res: tuple 

int

In [26]:
#CLEAN
# only get the ngram counts of the clickbait ; T
d_neg_ngrams_counts = count_ngrams(clickbait_l_c)
d_pos_ngrams_counts = count_ngrams(nonclickbait_l_c)

In [27]:
#CLEAN
def get_counts(list1, counted_ngrams):
    counts = []
    list1_ngrams = generate_ngrams(list1)
    list2_counts = counted_ngrams
    
    for length in range(param_span,0, -1):
        for v in list1_ngrams[length]:
            counts.append([list2_counts[length][v], v])
    return np.array(counts)

# return: 
# array([[1, ('Masuk', 'Radar', 'Pilwalkot')],
#        [1, ('Radar', 'Pilwalkot', 'Medan,')]])

In [28]:
#d_neg_ngrams_counts
dneg = d_neg_ngrams_counts[2]
type(dneg)

collections.Counter

In [29]:
#CLEAN
#these are methods that will become useful when extracting attribute markers
#why do we need all this? well... that's like 5 hours of debugging...
def flatten(foo):
    return list(_flatten(foo))

def _flatten(foo):
    for x in foo:
        if isinstance(x, collections.Iterable) and not isinstance(x, str):
            for y in _flatten(x):
                yield y
        else:
            yield x

def array_to_string(a):
    return ' '.join(flatten(a))

def is_in_string_array(elements, original): #deprecated, does not take into account sequence order
    return np.isin(array_to_string(elements).split(), array_to_string(original).split()).any()

def insert_string(string, inserted_string, index):
    return string[:index] + inserted_string + string[index:]

# modified from https://stackoverflow.com/questions/41752946/replacing-a-character-from-a-certain-index
def replace_string(s, newstring, index, nofail=False):
    # raise an error if index is outside of the string
    if not nofail and index not in range(len(s)):
        raise ValueError("index outside given string. index:" + index)

    # if not erroring, but the index is still not in the correct range..
    if index < 0:  # add it to the beginning
        return newstring + s
    if index > len(s):  # add it to the end
        return s + newstring

    # insert the new string between "slices" of the original
    return s[:index] + newstring + s[index + len(newstring):]

In [30]:
#CLEAN

param_threshold = 5

def get_attribute_markers(s, style_src):
    sentence = [s]
    
    ngrams = get_counts(sentence, d_pos_ngrams_counts)
    if len(ngrams) > 0:
        ngrams = ngrams[:,1]
    
    pos_counts = get_counts(sentence, d_pos_ngrams_counts)
    if len(pos_counts) > 0:
        pos_counts = pos_counts[:,0]
    
    neg_counts = get_counts(sentence, d_neg_ngrams_counts)
    if len(neg_counts) > 0:
        neg_counts = neg_counts[:,0]

    print('test' , neg_counts)
    
    
    if(style_src):
        importances = (pos_counts + param_smooth) / (neg_counts + param_smooth)
    else:
        importances = (neg_counts + param_smooth) / (pos_counts + param_smooth)
        
    a = []
    
    importances = np.vstack((importances, ngrams)).T
    for importance in importances:
        if importance[0] > param_threshold and not is_in_string_array(importance[1], a):
            a.append(' '.join(importance[1]))
    return a

def separate(sentence, style_src):
    attributes = get_attribute_markers(sentence, style_src)
    c = sentence

    replace_indexes = []
    for a in attributes:
        replace_index = -1
        replace_index = c.find(a)
        replace_indexes.append(replace_index)
        c = c.replace(a, " "*len(a))
        
    if len(attributes) == 0:
        return {'c': c, 'a': [], 'i': [], 's': sentence}
    
    replace_indexes, attributes = zip(*sorted(zip(replace_indexes, attributes)))
    return {'c': c, 'a': attributes, 'i': replace_indexes, 's': sentence}

def get_c(sentence, style):
    return re.sub(' +', ' ', separate(sentence, style)['c'])

def get_a(sentence, style):
    a = separate(sentence, style)['a']
    if len(a) > 0:
        return ' '.join(a)
    else:
        return ""

In [31]:
cres = get_attribute_markers("Viral! Ini Kocak Kabur", 0)
cres

test [0 0 0 0 0 0 8 8 8 881 13 5]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if __name__ == '__main__':


['Viral!', 'Ini', 'Kocak', 'Kabur']

In [32]:
# CLEAN
def get_c(sentence, style):
    return re.sub(' +', ' ', separate(sentence, style)['c'])

def get_a(sentence, style):
    a = separate(sentence, style)['a']
    if len(a) > 0:
        return ' '.join(a)
    else:
        return ""

In [33]:
testdc = get_c("Viral! Ini Berikut Ini Alasanya", 0)
testdc

test [0 0 0 0 0 0 8 0 8 8 8 881 27 881 0]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  # Remove the CWD from sys.path while we load stuff.


' Ini Alasanya'

In [34]:
s = "Viral! Ini Berikut Ini Alasanya" #4 words
style_src = 0
sentence = [s]

In [35]:
pos_counts = get_counts(sentence, d_pos_ngrams_counts)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  # Remove the CWD from sys.path while we load stuff.


In [36]:
pos_counts

array([[0, ('Viral!', 'Ini', 'Berikut')],
       [0, ('Ini', 'Berikut', 'Ini')],
       [0, ('Berikut', 'Ini', 'Alasanya')],
       [0, ('Viral!', 'Ini')],
       [0, ('Viral!', 'Ini')],
       [0, ('Ini', 'Berikut')],
       [0, ('Berikut', 'Ini')],
       [0, ('Ini', 'Alasanya')],
       [0, ('Viral!',)],
       [0, ('Viral!',)],
       [0, ('Viral!',)],
       [86, ('Ini',)],
       [0, ('Berikut',)],
       [86, ('Ini',)],
       [0, ('Alasanya',)]], dtype=object)

In [37]:
neg_counts = get_counts(sentence, d_neg_ngrams_counts)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  # Remove the CWD from sys.path while we load stuff.


In [38]:
neg_counts

array([[0, ('Viral!', 'Ini', 'Berikut')],
       [0, ('Ini', 'Berikut', 'Ini')],
       [0, ('Berikut', 'Ini', 'Alasanya')],
       [0, ('Viral!', 'Ini')],
       [0, ('Viral!', 'Ini')],
       [0, ('Ini', 'Berikut')],
       [8, ('Berikut', 'Ini')],
       [0, ('Ini', 'Alasanya')],
       [8, ('Viral!',)],
       [8, ('Viral!',)],
       [8, ('Viral!',)],
       [881, ('Ini',)],
       [27, ('Berikut',)],
       [881, ('Ini',)],
       [0, ('Alasanya',)]], dtype=object)

In [95]:
ngrams = get_counts(sentence, d_pos_ngrams_counts)
if len(ngrams) > 0:
    ngrams = ngrams[:,1]

pos_counts = get_counts(sentence, d_pos_ngrams_counts)
if len(pos_counts) > 0:
    pos_counts = pos_counts[:,0]

neg_counts = get_counts(sentence, d_neg_ngrams_counts)
if len(neg_counts) > 0:
    neg_counts = neg_counts[:,0]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  # Remove the CWD from sys.path while we load stuff.


In [40]:
pos_counts

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 86, 0, 86, 0], dtype=object)

In [41]:
neg_counts

array([0, 0, 0, 0, 0, 0, 8, 0, 8, 8, 8, 881, 27, 881, 0], dtype=object)

In [42]:
pos_counts

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 86, 0, 86, 0], dtype=object)

In [43]:
neg_counts

array([0, 0, 0, 0, 0, 0, 8, 0, 8, 8, 8, 881, 27, 881, 0], dtype=object)

In [94]:
ngrams = get_counts(sentence, d_pos_ngrams_counts)
if len(ngrams) > 0:
    ngrams = ngrams[:,1]

pos_counts = get_counts(sentence, d_pos_ngrams_counts)
if len(pos_counts) > 0:
    pos_counts_sl = pos_counts[:,0]

neg_counts = get_counts(sentence, d_neg_ngrams_counts)
if len(neg_counts) > 0:
    neg_counts_sl = neg_counts[:,0]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  # Remove the CWD from sys.path while we load stuff.


In [45]:
pos_counts_sl

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 86, 0, 86, 0], dtype=object)

In [96]:
top = (neg_counts + param_smooth)
top

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=object)

In [97]:
bottom = (pos_counts + param_smooth)
bottom

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 10, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=object)

In [98]:
importances = (neg_counts + param_smooth) / (pos_counts + param_smooth)

In [99]:
importances

array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 0.1, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 1.0, 1.0], dtype=object)

In [100]:
#importance of post neg; 
importances = (pos_counts + param_smooth) / (neg_counts + param_smooth)

In [101]:
importances

array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 10.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 1.0, 1.0], dtype=object)

In [102]:
importances = np.vstack((importances, ngrams)).T

In [103]:
importances

array([[1.0, ('T', 'h', 'i')],
       [1.0, ('h', 'i', 's')],
       [1.0, ('i', 's', 'i')],
       [1.0, ('s', 'i', 's')],
       [1.0, ('i', 's', 'a')],
       [1.0, ('s', 'a', 's')],
       [1.0, ('a', 's', 'e')],
       [1.0, ('s', 'e', 'n')],
       [1.0, ('e', 'n', 't')],
       [1.0, ('n', 't', 'e')],
       [1.0, ('t', 'e', 'n')],
       [1.0, ('e', 'n', 'c')],
       [1.0, ('n', 'c', 'e')],
       [1.0, ('T', 'h')],
       [1.0, ('h', 'i')],
       [1.0, ('i', 's')],
       [1.0, ('s', 'i')],
       [1.0, ('i', 's')],
       [1.0, ('s', 'a')],
       [1.0, ('a', 's')],
       [1.0, ('s', 'e')],
       [1.0, ('e', 'n')],
       [1.0, ('n', 't')],
       [1.0, ('t', 'e')],
       [1.0, ('e', 'n')],
       [1.0, ('n', 'c')],
       [1.0, ('c', 'e')],
       [10.0, ('T',)],
       [1.0, ('h',)],
       [1.0, ('i',)],
       [1.0, ('s',)],
       [1.0, ('i',)],
       [1.0, ('s',)],
       [2.0, ('a',)],
       [1.0, ('s',)],
       [1.0, ('e',)],
       [1.0, ('n',)],
       [1.0,

In [110]:
ngrams = get_counts(sentence, d_pos_ngrams_counts)
if len(ngrams) > 0:
  ngrams = ngrams[:,1]

pos_counts = get_counts(sentence, d_pos_ngrams_counts)
if len(pos_counts) > 0:
  pos_counts = pos_counts[:,0]

neg_counts = get_counts(sentence, d_neg_ngrams_counts)
if len(neg_counts) > 0:
  neg_counts = neg_counts[:,0]

print('test' , neg_counts)

if(style_src):
  importances = (pos_counts + param_smooth) / (neg_counts + param_smooth)
else:
  importances = (neg_counts + param_smooth) / (pos_counts + param_smooth)
  
a = []

importances = np.vstack((importances, ngrams)).T
for importance in importances:
  if importance[0] > param_threshold and not is_in_string_array(importance[1], a):
    a.append(' '.join(importance[1]))

    


IndentationError: ignored

### Created By Myself

In [205]:
# bikin tokenization fucntion with nltk; 
import nltk
from nltk.util import ngrams
nltk.download('punkt')

# create the ngram of the list of sentence, 
# sentence_ex: list of sentence
# min_length : minimal sentence
# max_length : maximal len
# return dict: 1,2 each with list of ngram of size n

from collections import Counter

def ngram_maker(list_sentences, min_length, max_length):
  lengths = range(min_length, max_length + 1)
  res_ngram = {length : [] for length in lengths}

  for leng in lengths:
    for sentence in list_sentences:
      n_grams = ngrams(nltk.word_tokenize(sentence), leng)
      for gram in n_grams: 
        temp_word = ' '.join(gram)
        res_ngram[leng].append(temp_word)
  
  return res_ngram

def ngram_maker_v2(list_sentences, min_length, max_length):
  lengths = range(min_length, max_length + 1)
  res_ngram = {length : [] for length in lengths}

  for leng in lengths:
    for sentence in list_sentences:
      temp_set = set()
      n_grams = ngrams(nltk.word_tokenize(sentence), leng)

      for grams in n_grams:
        res = ' '.join(grams)
        temp_set.add(res)
      
      sentence_split = sentence.split()
      n_grams_split = nltk.ngrams(sentence_split, leng)
      
      for grams in n_grams_split:
        res = ' '.join(grams)
        temp_set.add(res) 

      # print(temp_set)

      for key in temp_set:
        res_ngram[leng].append(key)

  return res_ngram

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
# counting the occurce of the ngram
def counter_for_ngram(ngram_dict, min_length, max_length):
  lengths = range(min_length, max_length + 1)
  ngram_count_res = {length : [] for length in lengths}
  
  for key in ngram_dict:
    ng_count = Counter(ngram_dict[key])
    ngram_count_res[key] = ng_count 

  return ngram_count_res

In [206]:
clickbait_ngrams_v2= ngram_maker_v2(list_sentences=clickbait_l_c, min_length=1, max_length=2)
clickbait_ngram_count_v2 = counter_for_ngram(ngram_dict=clickbait_ngrams_v2,min_length=1, max_length=2)

In [ ]:
clickbait_ngram_count_v2

In [207]:
# final ngram for clickabait and nonclickbait
clickbait_ngrams= ngram_maker_v2(list_sentences=clickbait_l_c, min_length=1, max_length=2)
clickbait_ngram_count = counter_for_ngram(ngram_dict=clickbait_ngrams,min_length=1, max_length=2)

nonclickbait_ngrams = ngram_maker_v2(list_sentences=nonclickbait_l_c, min_length=1, max_length=2)
nonclickbait_ngram_count = counter_for_ngram(ngram_dict=nonclickbait_ngrams,min_length=1, max_length=2)

In [ ]:
nonclickbait_ngram_count

In [ ]:
len(clickbait_ngrams)
type(clickbait_ngram_count[2])
clickbait_ngram_count

In [162]:
clickbait_ngram_count[2]['Ini Alasanya']

0



##### Get Ngram from Sentence Only

In [165]:



# get ngram from the word in the sentence example
def ngram_from_sentence_v2(ori_sentence, min_length, max_length):
  sent_in_arr = [ori_sentence]
  lengths = range(min_length, max_length + 1)
  res_ngram_sentence = []

  for leng in lengths: 
      for sentence in sent_in_arr: 
        n_grams = ngrams(nltk.word_tokenize(sentence), leng)
        for grams in n_grams:
          res = ' '.join(grams)
          if res not in res_ngram_sentence: 
            res_ngram_sentence.append(res) 
  
  return res_ngram_sentence

# get ngram from the word in the sentence example
def ngram_from_sentence_v1(ori_sentence, min_length, max_length):
  sent_in_arr = [ori_sentence]
  lengths = range(min_length, max_length + 1)
  res_ngram_sentence = []

  for leng in lengths: 
      for sentence in sent_in_arr: 
        # sentence_split = sentence.split()
        n_grams = ngrams(nltk.word_tokenize(sentence), leng)
        for grams in n_grams:
          res = ' '.join(grams)
          res_ngram_sentence.append(res)
  
  return res_ngram_sentence


In [164]:
sentence = "Viral! Ini Alasanya Wow Kabur Gadjah Kebun Binatang !"
sentence_ngram_ref_v2 = ngram_from_sentence_v2(ori_sentence=sentence, min_length=1, max_length=2)
sentence_ngram_ref_v1 = ngram_from_sentence_v1(ori_sentence=sentence, min_length=1, max_length=2)

In [167]:
# get ngram from the word in the sentence reference only
def ngram_from_sentence_v3(ori_sentence, min_length, max_length):
  sent_in_arr = [ori_sentence]
  lengths = range(min_length, max_length + 1)
  res_ngram_sentence = []

  for leng in lengths: 
      for sentence in sent_in_arr: 
        n_grams = ngrams(nltk.word_tokenize(sentence), leng)
        for grams in n_grams:
          res = ' '.join(grams)
          if res not in res_ngram_sentence: 
            res_ngram_sentence.append(res)  
        
        sentence_split = sentence.split()
        n_grams_split = nltk.ngrams(sentence_split, leng)

        for grams in n_grams_split:
          res = ' '.join(grams)
          if res not in res_ngram_sentence: 
            res_ngram_sentence.append(res)  
  
  return res_ngram_sentence

# get  counter based on the sentence and compare to the ngram dictionary
def count_ngram_sentence_only(ngram_dictionary, ngram_from_sentence, min_length, max_length):  
  lengths = range(min_length, max_length + 1)

  ngram_compare_dict = {}
  ngram_compare_arr = []
  
  for key in lengths:  
    for split in ngram_from_sentence:
      # print(split)
      for ngram_list in ngram_dictionary[key].items():
        word_freq = ngram_list[0] 
        if split == word_freq:
          if split in ngram_compare_dict:
            ngram_compare_dict[split] = max(ngram_compare_dict[split], ngram_dictionary[key][split])  
          ngram_compare_dict[split] = ngram_dictionary[key][split]
        elif split not in ngram_compare_dict:
          ngram_compare_dict[split] = 0
  
  for key, val in ngram_compare_dict.items():
    ngram_compare_arr.append([key, val])
  
  return np.array(ngram_compare_arr)

In [ ]:
sentence_ngram_ref_v3 = ngram_from_sentence_v3(ori_sentence=sentence, min_length=1, max_length=2)

In [220]:
sentence_ngram_ref_v3

['Viral',
 '!',
 'Ini',
 'Alasanya',
 'Wow',
 'Kabur',
 'Gadjah',
 'Kebun',
 'Binatang',
 'Viral!',
 'Viral !',
 '! Ini',
 'Ini Alasanya',
 'Alasanya Wow',
 'Wow Kabur',
 'Kabur Gadjah',
 'Gadjah Kebun',
 'Kebun Binatang',
 'Binatang !',
 'Viral! Ini']

##### Stratch Saleince Func piece by piece

In [210]:
# return the count ngram from the sentence only, but not the same after all

sentence = "Viral! Ini Kocak Wow Kabur Gadjah Kebun Binatang"
sentence_ngram_ref = ngram_from_sentence_v3(ori_sentence=sentence, min_length=1, max_length=2)


counts_sentence_clickbait = count_ngram_sentence_only(clickbait_ngram_count,sentence_ngram_ref,1,2)
counts_sentence_nonclickbait = count_ngram_sentence_only(nonclickbait_ngram_count,sentence_ngram_ref,1,2)


In [169]:
sentence_ngram_ref

['Viral',
 '!',
 'Ini',
 'Kocak',
 'Wow',
 'Kabur',
 'Gadjah',
 'Kebun',
 'Binatang',
 'Viral!',
 'Viral !',
 '! Ini',
 'Ini Kocak',
 'Kocak Wow',
 'Wow Kabur',
 'Kabur Gadjah',
 'Gadjah Kebun',
 'Kebun Binatang',
 'Viral! Ini']

In [170]:
counts_sentence_nonclickbait

array([['Viral', '0'],
       ['!', '5'],
       ['Ini', '111'],
       ['Kocak', '1'],
       ['Wow', '0'],
       ['Kabur', '0'],
       ['Gadjah', '0'],
       ['Kebun', '5'],
       ['Binatang', '2'],
       ['Viral!', '0'],
       ['Viral !', '0'],
       ['! Ini', '0'],
       ['Ini Kocak', '0'],
       ['Kocak Wow', '0'],
       ['Wow Kabur', '0'],
       ['Kabur Gadjah', '0'],
       ['Gadjah Kebun', '0'],
       ['Kebun Binatang', '0'],
       ['Viral! Ini', '0']], dtype='<U21')

In [171]:
counts_sentence_clickbait

array([['Viral', '92'],
       ['!', '257'],
       ['Ini', '920'],
       ['Kocak', '19'],
       ['Wow', '0'],
       ['Kabur', '5'],
       ['Gadjah', '0'],
       ['Kebun', '1'],
       ['Binatang', '0'],
       ['Viral!', '8'],
       ['Viral !', '8'],
       ['! Ini', '5'],
       ['Ini Kocak', '0'],
       ['Kocak Wow', '0'],
       ['Wow Kabur', '0'],
       ['Kabur Gadjah', '0'],
       ['Gadjah Kebun', '0'],
       ['Kebun Binatang', '0'],
       ['Viral! Ini', '0']], dtype='<U21')

In [172]:
counts_sentence_nonclickbait[:, 1]

array(['0', '5', '111', '1', '0', '0', '0', '5', '2', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0'], dtype='<U21')

In [173]:
counts_sentence_clickbait[:, 1]

array(['92', '257', '920', '19', '0', '5', '0', '1', '0', '8', '8', '5',
       '0', '0', '0', '0', '0', '0', '0'], dtype='<U21')

In [211]:
num_arr_c_s_clickbait = []
num_arr_c_s_nonclickbait = []

if len(counts_sentence_clickbait) > 0:
  num_arr_c_s_clickbait = counts_sentence_clickbait[:, 1]


if len(counts_sentence_nonclickbait) > 0:
  num_arr_c_s_nonclickbait = counts_sentence_nonclickbait[:, 1]

In [212]:
num_arr_c_s_clickbait

array(['92', '257', '920', '19', '0', '5', '0', '1', '0', '8', '8', '5',
       '0', '0', '0', '0', '0', '0', '0'], dtype='<U21')

In [213]:
num_arr_c_s_nonclickbait

array(['0', '5', '111', '1', '0', '0', '0', '5', '2', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0'], dtype='<U21')

In [177]:
# convert u21 to int 
arr_gram_sentence_int_clickbait = num_arr_c_s_clickbait.astype(int)
arr_gram_sentence_int_nonclickbait = num_arr_c_s_nonclickbait.astype(int)

In [178]:
arr_gram_sentence_int_clickbait

array([ 92, 257, 920,  19,   0,   5,   0,   1,   0,   8,   8,   5,   0,
         0,   0,   0,   0,   0,   0])

In [179]:
# Count the salience

smoothing_parameter = 1

top = (arr_gram_sentence_int_clickbait + smoothing_parameter)
bottom = (arr_gram_sentence_int_nonclickbait + smoothing_parameter)

# top = np.add(arr_gram_sentence_int_clickbait, 1)



In [183]:
importances = (top/bottom)

In [184]:
importances

array([93.        , 43.        ,  8.22321429, 10.        ,  1.        ,
        6.        ,  1.        ,  0.33333333,  0.33333333,  9.        ,
        9.        ,  6.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ])

In [185]:
importances_arr = np.array([importances])

In [188]:
de = counts_sentence_clickbait[:, 0]
importances_t = np.vstack((importances, de)).T

In [189]:
importances_t

array([['93.0', 'Viral'],
       ['43.0', '!'],
       ['8.223214285714286', 'Ini'],
       ['10.0', 'Kocak'],
       ['1.0', 'Wow'],
       ['6.0', 'Kabur'],
       ['1.0', 'Gadjah'],
       ['0.3333333333333333', 'Kebun'],
       ['0.3333333333333333', 'Binatang'],
       ['9.0', 'Viral!'],
       ['9.0', 'Viral !'],
       ['6.0', '! Ini'],
       ['1.0', 'Ini Kocak'],
       ['1.0', 'Kocak Wow'],
       ['1.0', 'Wow Kabur'],
       ['1.0', 'Kabur Gadjah'],
       ['1.0', 'Gadjah Kebun'],
       ['1.0', 'Kebun Binatang'],
       ['1.0', 'Viral! Ini']], dtype='<U32')

In [190]:
importances_t[:,0]

array(['93.0', '43.0', '8.223214285714286', '10.0', '1.0', '6.0', '1.0',
       '0.3333333333333333', '0.3333333333333333', '9.0', '9.0', '6.0',
       '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0'], dtype='<U32')

In [191]:
# convert the list into numpy  

importances_int = importances_t.copy()

new_imp = [];


for imp in importances_int:
  new_imp.append([float(imp[0]), imp[1].split()])

new_imp_numpy = np.array(new_imp)

    

In [193]:
new_imp_numpy

array([[93.0, list(['Viral'])],
       [43.0, list(['!'])],
       [8.223214285714286, list(['Ini'])],
       [10.0, list(['Kocak'])],
       [1.0, list(['Wow'])],
       [6.0, list(['Kabur'])],
       [1.0, list(['Gadjah'])],
       [0.3333333333333333, list(['Kebun'])],
       [0.3333333333333333, list(['Binatang'])],
       [9.0, list(['Viral!'])],
       [9.0, list(['Viral', '!'])],
       [6.0, list(['!', 'Ini'])],
       [1.0, list(['Ini', 'Kocak'])],
       [1.0, list(['Kocak', 'Wow'])],
       [1.0, list(['Wow', 'Kabur'])],
       [1.0, list(['Kabur', 'Gadjah'])],
       [1.0, list(['Gadjah', 'Kebun'])],
       [1.0, list(['Kebun', 'Binatang'])],
       [1.0, list(['Viral!', 'Ini'])]], dtype=object)

In [196]:
param_threshold = 6.5

attribute = []
whole_attribute = []

# importances = np.vstack((importances, counts_sentence_nonclickbait)).T
for importance in new_imp_numpy:
    print(importance)

    if importance[0] > param_threshold: 
      whole_attribute.append(" ".join(importance[1]))

    if importance[0] > param_threshold and not is_in_string_array(importance[1], attribute):
        attribute.append(' '.join(importance[1]))

[93.0 list(['Viral'])]
[43.0 list(['!'])]
[8.223214285714286 list(['Ini'])]
[10.0 list(['Kocak'])]
[1.0 list(['Wow'])]
[6.0 list(['Kabur'])]
[1.0 list(['Gadjah'])]
[0.3333333333333333 list(['Kebun'])]
[0.3333333333333333 list(['Binatang'])]
[9.0 list(['Viral!'])]
[9.0 list(['Viral', '!'])]
[6.0 list(['!', 'Ini'])]
[1.0 list(['Ini', 'Kocak'])]
[1.0 list(['Kocak', 'Wow'])]
[1.0 list(['Wow', 'Kabur'])]
[1.0 list(['Kabur', 'Gadjah'])]
[1.0 list(['Gadjah', 'Kebun'])]
[1.0 list(['Kebun', 'Binatang'])]
[1.0 list(['Viral!', 'Ini'])]


In [197]:
attribute

['Viral', '!', 'Ini', 'Kocak', 'Viral!']

In [198]:
whole_attribute

['Viral', '!', 'Ini', 'Kocak', 'Viral!', 'Viral !']

In [199]:
sentence

'Viral! Ini Kocak Wow Kabur Gadjah Kebun Binatang'

In [200]:
res_sentence = ' '.join(filter(lambda x: x not in attribute,  sentence.split()))

In [201]:
sentence.split()

['Viral!', 'Ini', 'Kocak', 'Wow', 'Kabur', 'Gadjah', 'Kebun', 'Binatang']

In [202]:
res_sentence

'Wow Kabur Gadjah Kebun Binatang'

##### Clean Salience FUNC

In [ ]:
#CLEAN
#these are methods that will become useful when extracting attribute markers
#why do we need all this? well... that's like 5 hours of debugging...
def flatten(foo):
    return list(_flatten(foo))

def _flatten(foo):
    for x in foo:
        if isinstance(x, collections.Iterable) and not isinstance(x, str):
            for y in _flatten(x):
                yield y
        else:
            yield x

def array_to_string(a):
    return ' '.join(flatten(a))

def is_in_string_array(elements, original): #deprecated, does not take into account sequence order
    return np.isin(array_to_string(elements).split(), array_to_string(original).split()).any()

def insert_string(string, inserted_string, index):
    return string[:index] + inserted_string + string[index:]

# modified from https://stackoverflow.com/questions/41752946/replacing-a-character-from-a-certain-index
def replace_string(s, newstring, index, nofail=False):
    # raise an error if index is outside of the string
    if not nofail and index not in range(len(s)):
        raise ValueError("index outside given string. index:" + index)

    # if not erroring, but the index is still not in the correct range..
    if index < 0:  # add it to the beginning
        return newstring + s
    if index > len(s):  # add it to the end
        return s + newstring

    # insert the new string between "slices" of the original
    return s[:index] + newstring + s[index + len(newstring):]

In [217]:
smoothing_parameter = 1
sentence = "Viral! Ini Kocak Wow Kabur Gadjah Kebun Binatang"


def salience_func(sentence, min_length, max_length, ref_bait):
  
  # ngram sentence as referenc
  sentence_ngram_ref = ngram_from_sentence_v3(ori_sentence=sentence, min_length=min_length, max_length=max_length)

  # count the clickbait sentence, clickbait ngram count as based reference
  counts_sentence_clickbait = count_ngram_sentence_only(clickbait_ngram_count,sentence_ngram_ref,min_length,max_length)
  
  # count the non-clickbait sentence, non-clickbait ngram count as based reference
  counts_sentence_nonclickbait = count_ngram_sentence_only(nonclickbait_ngram_count,sentence_ngram_ref,min_length,max_length)

  num_arr_c_s_clickbait = []
  num_arr_c_s_nonclickbait = []

  # check if the length more than 0, then take the array of number
  if len(counts_sentence_clickbait) > 0:
    num_arr_c_s_clickbait = counts_sentence_clickbait[:, 1]

  # check if the length more than 0, then take the array of number
  if len(counts_sentence_nonclickbait) > 0:
    num_arr_c_s_nonclickbait = counts_sentence_nonclickbait[:, 1]

  # convert u21 to int 
  arr_gram_sentence_int_clickbait = num_arr_c_s_clickbait.astype(int)
  arr_gram_sentence_int_nonclickbait = num_arr_c_s_nonclickbait.astype(int)

  importance = 0

  # Count the SALIENCE if non-clickbait to clickbait
  if ref_bait == "non-to-click":
    top = (arr_gram_sentence_int_clickbait + smoothing_parameter)
    bottom = (arr_gram_sentence_int_nonclickbait + smoothing_parameter)
    importances = (top/bottom)
  else : 
    top = (arr_gram_sentence_int_nonclickbait+ smoothing_parameter)
    bottom = (arr_gram_sentence_int_clickbait + smoothing_parameter)
    importances = (top/bottom)

  # combine the words and also the salience calculation
  de = counts_sentence_clickbait[:, 0]
  importances_t = np.vstack((importances, de)).T

  # get the new list of importance and split ngram and make it array
  new_imp = [];
  for imp in importances_t:
    new_imp.append([float(imp[0]), imp[1].split()])
  new_imp_numpy = np.array(new_imp)

  param_threshold = 6.5

  # get the attribute
  attribute_set = []

  # importances = np.vstack((importances, counts_sentence_nonclickbait)).T
  for importance in new_imp_numpy:

      if importance[0] > param_threshold and not is_in_string_array(importance[1], attribute):
          attribute_set.append(' '.join(importance[1]))

  # the fact sentence only without any attribute 
  clean_sentence = ' '.join(filter(lambda x: x not in attribute_set,  sentence.split()))

  # return the attribute set, clean_sentence
  return attribute_set, clean_sentence


att, clean_sentence = salience_func(sentence, 1, 2, "non-to-click")


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:45: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.


## RETRIEVE FUNC


# DRAFT KOTOR

In [ ]:
#v3
# ['Viral',
#  '!',
#  'Ini',
#  'Alasanya',
#  'Wow',
#  'Kabur',
#  'Gadjah',
#  'Kebun',
#  'Binatang',
#  'Viral!',
#  'Viral !',
#  '! Ini',
#  'Ini Alasanya',
#  'Alasanya Wow',
#  'Wow Kabur',
#  'Kabur Gadjah',
#  'Gadjah Kebun',
#  'Kebun Binatang',
#  'Binatang !',
#  'Viral! Ini']

#v2
# ['Viral',
#  '!',
#  'Ini',
#  'Alasanya',
#  'Wow',
#  'Kabur',
#  'Gadjah',
#  'Kebun',
#  'Binatang',
#  '!',
#  'Viral !',
#  '! Ini',
#  'Ini Alasanya',
#  'Alasanya Wow',
#  'Wow Kabur',
#  'Kabur Gadjah',
#  'Gadjah Kebun',
#  'Kebun Binatang',
#  'Binatang !']


#v1
# ['Viral',
#  '!',
#  'Ini',
#  'Alasanya',
#  'Wow',
#  'Kabur',
#  'Gadjah',
#  'Kebun',
#  'Binatang',
#  'Viral !',
#  '! Ini',
#  'Ini Alasanya',
#  'Alasanya Wow',
#  'Wow Kabur',
#  'Kabur Gadjah',
#  'Gadjah Kebun',
#  'Kebun Binatang',
#  'Binatang !']

In [ ]:
# for key in lengths:
#   for split in ngram_from_sentence:
#     for ngrams_list in ngram_dictionary[key].items():
#           wordn = ngrams_list[0] 
#           if wordn == split: 
#               temp_arr = []
#               temp_arr.insert(0, ngrams_list[1])
#               temp_arr.insert(1, wordn)

#               ngram_compare_dict[split] = ngrams_list[1]
#               print(ngram_compare_dict)

#               ngram_compare_arr.append(temp_arr)

#           else: 
#               ngram_compare_dict[split] = 0

In [218]:
sentence = "This is a sentence!"
words = sentence.split()

bi_grams = nltk.ngrams(words, 2)

for gram in bi_grams:
    print(gram)

('This', 'is')
('is', 'a')
('a', 'sentence!')


In [182]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a,b))

d = c.T
d

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# result of the ngram that only use here; 
new_ngram_coll

{1: Counter({'!': 307,
          'Bingung': 6,
          'CCTV': 1,
          'Cari': 9,
          'Ini': 922,
          'Jakut': 4,
          'Jalan': 29,
          'Kabur': 5,
          'Kocak': 19,
          'Maling': 3,
          'Mewah': 20,
          'Rumah': 56,
          'Terekam': 4,
          'Viral': 92,
          'di': 717}),
 2: Counter({'! Ini': 5,
          'Bingung Cari': 1,
          'CCTV Bingung': 1,
          'Cari Jalan': 1,
          'Jakut Terekam': 1,
          'Jalan Kabur': 1,
          'Maling di': 1,
          'Mewah Jakut': 1,
          'Rumah Mewah': 1,
          'Terekam CCTV': 1,
          'Viral !': 8,
          'di Rumah': 10})}

In [ ]:
items = ngram_count_res[1].items()
for it in items: 
  print(it)

In [ ]:
cres = get_attribute_markers("Viral! Ini Kocak Wow Maling di Rumah Mewah Jakut Terekam CCTV Bingung Cari Jalan Kabur", 0)
cres

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if __name__ == '__main__':


['Viral!', 'Ini', 'Kocak', 'Kabur']

In [ ]:
a= get_a("Viral! Ini Berikut Kocak Wow Maling di Rumah Mewah Jakut Terekam CCTV Bingung Cari Jalan Kabur", 0)
a

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if __name__ == '__main__':


'Viral! Ini Berikut Kocak Kabur'

In [ ]:
test_l_dfdf = ['Masuk Radar Pilwalkot Medan, Menantu Jokowi Bertemu DPW NasDem Sumut',
 'Malaysia Sudutkan RI: Isu Kabut Asap hingga Invasi Babi',
 'Kemensos Salurkan Rp 7,3 M bagi Korban Kerusuhan Sosial di Papua',
 'MPR: Amandemen UUD 1945 Tak Akan Melebar ke Mana-mana']

In [ ]:
# generate ngrams

lines = nonclickbait_l_c

lengths = range(min_length, max_length + 1)
ngrams = {length: [] for length in lengths}
queue = collections.deque(maxlen=max_length)

def add_queue():
    current = tuple(queue)
    for length in lengths:
        if len(current) >= length and not has_punctuation(current[:length]):
            ngrams[length].append(current[:length])

short_by = 0
for line in lines:
    short_by = max(0, max_length - len(lines))
    for word in line.split():
        queue.append(word)
        if len(queue) >= max_length-short_by:
            add_queue()                

while len(queue) > min_length:
    queue.popleft()
    add_queue()


In [ ]:
test_clickbait

# type(test_clickabit[3])

{1: Counter({('Viral!',): 8,
          ('Driver',): 5,
          ('Ojol',): 6,
          ('di',): 716,
          ('Bekasi',): 6,
          ('Antar',): 5,
          ('Pesanan',): 2,
          ('Makanan',): 15,
          ('Pakai',): 73,
          ('Sepeda',): 8,
          ('Ada',): 89,
          ('Motor',): 22,
          ('Nyangkut',): 2,
          ('Atas',): 11,
          ('Bambu',): 2,
          ('Sleman,',): 3,
          ('Kok',): 10,
          ('Bisa?',): 7,
          ('Pesan',): 28,
          ('Gamblang',): 1,
          ('Poyuono',): 1,
          ('Menolak',): 2,
          ('Revisi',): 22,
          ('UU',): 26,
          ('KPK',): 48,
          ('Kocak!',): 2,
          ('Maling',): 3,
          ('Rumah',): 49,
          ('Mewah',): 16,
          ('Jakut',): 4,
          ('Terekam',): 4,
          ('CCTV',): 1,
          ('Bingung',): 5,
          ('Cari',): 9,
          ('Jalan',): 26,
          ('Kabur',): 5,
          ('Viral',): 71,
          ('Video',): 78,
          ('Diduga'

In [ ]:
test_get = get_counts(["Masuk Radar Pilwalkot Medan, Menantu Jokowi Bertemu DPW NasDem Sumut"], d_pos_ngrams_counts)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if __name__ == '__main__':


array([[1, ('Masuk', 'Radar', 'Pilwalkot')],
       [1, ('Radar', 'Pilwalkot', 'Medan,')],
       [1, ('Pilwalkot', 'Medan,', 'Menantu')],
       [1, ('Medan,', 'Menantu', 'Jokowi')],
       [1, ('Menantu', 'Jokowi', 'Bertemu')],
       [1, ('Jokowi', 'Bertemu', 'DPW')],
       [1, ('Bertemu', 'DPW', 'NasDem')],
       [1, ('DPW', 'NasDem', 'Sumut')],
       [1, ('Masuk', 'Radar')],
       [1, ('Masuk', 'Radar')],
       [1, ('Radar', 'Pilwalkot')],
       [1, ('Pilwalkot', 'Medan,')],
       [1, ('Medan,', 'Menantu')],
       [1, ('Menantu', 'Jokowi')],
       [4, ('Jokowi', 'Bertemu')],
       [1, ('Bertemu', 'DPW')],
       [1, ('DPW', 'NasDem')],
       [1, ('NasDem', 'Sumut')],
       [35, ('Masuk',)],
       [35, ('Masuk',)],
       [35, ('Masuk',)],
       [1, ('Radar',)],
       [5, ('Pilwalkot',)],
       [3, ('Medan,',)],
       [2, ('Menantu',)],
       [150, ('Jokowi',)],
       [21, ('Bertemu',)],
       [1, ('DPW',)],
       [2, ('NasDem',)],
       [17, ('Sumut',)]], dty

In [ ]:
test_get[20]

array([35, ('Masuk',)], dtype=object)

In [ ]:
d_neg_ngrams_counts

{1: Counter({('Viral!',): 8,
          ('Driver',): 5,
          ('Ojol',): 6,
          ('di',): 716,
          ('Bekasi',): 6,
          ('Antar',): 5,
          ('Pesanan',): 2,
          ('Makanan',): 15,
          ('Pakai',): 73,
          ('Sepeda',): 8,
          ('Ada',): 89,
          ('Motor',): 22,
          ('Nyangkut',): 2,
          ('Atas',): 11,
          ('Bambu',): 2,
          ('Sleman,',): 3,
          ('Kok',): 10,
          ('Bisa?',): 7,
          ('Pesan',): 28,
          ('Gamblang',): 1,
          ('Poyuono',): 1,
          ('Menolak',): 2,
          ('Revisi',): 22,
          ('UU',): 26,
          ('KPK',): 48,
          ('Kocak!',): 2,
          ('Maling',): 3,
          ('Rumah',): 49,
          ('Mewah',): 16,
          ('Jakut',): 4,
          ('Terekam',): 4,
          ('CCTV',): 1,
          ('Bingung',): 5,
          ('Cari',): 9,
          ('Jalan',): 26,
          ('Kabur',): 5,
          ('Viral',): 71,
          ('Video',): 78,
          ('Diduga'