In [3]:
import numpy as np
import pandas as pd

In [4]:
(lambda x: x*2)(12)

24

In [5]:
list_1 = [1,2,3,4,5,6,7,8,9]
filter(lambda x: x%2==0, list_1)

In [6]:
list(filter(lambda x: x%2==0, list_1))

[2, 4, 6, 8]

In [7]:
list_1 = [1,2,3,4,5,6,7,8,9]
cubed = map(lambda x: pow(x,3), list_1)
list(cubed)

[1, 8, 27, 64, 125, 216, 343, 512, 729]

In [8]:
df = pd.DataFrame({
    'Name': ['Luke','Gina','Sam','Emma'],
    'Status': ['Father', 'Mother', 'Son', 'Daughter'],
    'Birthyear': [1976, 1984, 2013, 2016],
})

df.head()

Name    Status  Birthyear
0  Luke    Father       1976
1  Gina    Mother       1984
2   Sam       Son       2013
3  Emma  Daughter       2016

In [9]:
df['age'] = df['Birthyear'].apply(lambda x: 2021-x)

In [10]:
df.age.head

<bound method NDFrame.head of 0    45
1    37
2     8
3     5
Name: age, dtype: int64>

In [11]:
# list(filter(lambda x: x>18, df['age']))
list(filter(lambda x: x> 18, df.age))

[45, 37]

In [12]:
df['double_age'] = df['age'].map(lambda x: x*2)

In [13]:
df['Gender'] = df['Status'].map(lambda x: 'Male' if x=='Father' or x=='son' else 'Female')

In [14]:
df.head()

Name    Status  Birthyear  age  double_age  Gender
0  Luke    Father       1976   45          90    Male
1  Gina    Mother       1984   37          74  Female
2   Sam       Son       2013    8          16  Female
3  Emma  Daughter       2016    5          10  Female

In [15]:
import re

def putSpace(input):

    # regex [A-Z][a-z]* means any string starting
    # with capital character followed by many
    # lowercase letters
    words = re.findall('[A-Z][a-z]*', input)

    print(words)

    # Change first letter of each word into lower
    # case
    for i in range(0,len(words)):
        words[i]=words[i][0].lower()+words[i][1:]

    print(words)
    print(' '.join(words))

# Driver program
if __name__ == "__main__":
    input = 'BruceWayneIsBatman'
    putSpace(input)

['Bruce', 'Wayne', 'Is', 'Batman']
['bruce', 'wayne', 'is', 'batman']
bruce wayne is batman


In [16]:
text_try = "digrebeg di hotel, aktor ftv ridho illahi berduaan dengan selebgram chagii wow! amelia?"

In [17]:
df['Status'] = df['Status'].replace({'.':' . ',', ':' , ', '!': " ! ", "?": " ? "},regex=True)


KeyboardInterrupt



In [ ]:
text_try = text_try.replace(".", " . " )

res_text = text_try.replace(",", " , " )

# res_text = text_try.replace({'.':' . ',', ':' , ', '!': " ! ", "?": " ? "}, )

print(res_text)

In [ ]:
rule = "([\D])([^\w^\s])([\s$\D])?"

text = "sering quality time bersama keluarga? ternyata ini 3,000 man,3 seperti manfaatnya!"

clean = re.compile(rule)
output = re.sub(clean, '\1 \2 \3' , text)

print(output)
# res = text.apply(lambda y: " ".join((re.sub(r'([!/?/./,/%/\'/\"/-/:])', lambda x: ' ' + x.group()+' ' , y)).split()) , 1)

# Chapter 16 – Natural Language Processing with RNNs and Attention

In [ ]:
import sys

assert sys.version_info >= (3, 7)

In [ ]:
# !conda install -c conda-forge tensorflow -y

In [ ]:
import tensorflow as tf

assert tf.__version__ >= "2.8.0"

In [ ]:
# !conda remove tensorflow -y

In [19]:
!pip3 install tensorflow

  Using cached tensorflow-2.9.2-cp38-cp38-macosx_10_14_x86_64.whl (228.6 MB)


In [ ]:
# !pip3 install --upgrade tensorflow==2.8

In [21]:
import tensorflow as tf

assert tf.__version__ >= "2.8.0"

/Users/nurrizkyimani/.conda/envs/workspace/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [ ]:
# !python -m pip show tensorflow

In [22]:
import matplotlib.pyplot as plt

plt.rc('font', size=14)
plt.rc('axes', labelsize=14, titlesize=14)
plt.rc('legend', fontsize=14)
plt.rc('xtick', labelsize=10)
plt.rc('ytick', labelsize=10)

In [23]:
from pathlib import Path

IMAGES_PATH = Path() / "images" / "nlp"
IMAGES_PATH.mkdir(parents=True, exist_ok=True)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = IMAGES_PATH / f"{fig_id}.{fig_extension}"
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

In [24]:
if not tf.config.list_physical_devices('GPU'):
    print("No GPU was detected. Neural nets can be very slow without a GPU.")
    if "google.colab" in sys.modules:
        print("Go to Runtime > Change runtime and select a GPU hardware "
              "accelerator.")
    if "kaggle_secrets" in sys.modules:
        print("Go to Settings > Accelerator and select GPU.")

No GPU was detected. Neural nets can be very slow without a GPU.


In [ ]:
# import tensorflow as tf
#
# assert tf.__version__ >= "2.8.0"

In [25]:
import tensorflow as tf

shakespeare_url = "https://homl.info/shakespeare"  # shortcut URL
filepath = tf.keras.utils.get_file("shakespeare.txt", shakespeare_url)
with open(filepath) as f:
    shakespeare_text = f.read()

In [26]:
# extra code – shows a short text sample
print(shakespeare_text[:80])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.


In [27]:
# extra code – shows all 39 distinct characters (after converting to lower case)
"".join(sorted(set(shakespeare_text.lower())))

"\n !$&',-.3:;?abcdefghijklmnopqrstuvwxyz"

In [28]:
# text_vec_layer = tf.keras.layers.TextVectorization(split="character",
#                                                    standardize="lower")
# text_vec_layer.adapt([shakespeare_text])
# encoded = text_vec_layer([shakespeare_text])[0]

2022-09-03 14:51:30.495327: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [ ]:
# !pip3 uninstall tf-nightly -y

In [35]:
import tensorflow as tf

assert tf.__version__ >= "2.8.0"

In [ ]:
tf.keras.layers.TextVectorization()

In [30]:
text_vec_layer = tf.keras.layers.TextVectorization(split="character",
                                                   standardize="lower")
text_vec_layer.adapt([shakespeare_text])
encoded = text_vec_layer([shakespeare_text])[0]

In [32]:
encoded -= 2  # drop tokens 0 (pad) and 1 (unknown), which we will not use
n_tokens = text_vec_layer.vocabulary_size() - 2  # number of distinct chars = 39
dataset_size = len(encoded)  # total number of chars = 1,115,394

In [34]:
encoded

<tf.Tensor: shape=(1115394,), dtype=int64, numpy=array([19,  5,  8, ..., 20, 26, 10])>

In [36]:
text_vec_layer

In [37]:
n_tokens

39

In [38]:
dataset_size

1115394

In [39]:
def to_dataset(sequence, length, shuffle=False, seed=None, batch_size=32):
    ds = tf.data.Dataset.from_tensor_slices(sequence)
    ds = ds.window(length + 1, shift=1, drop_remainder=True)
    ds = ds.flat_map(lambda window_ds: window_ds.batch(length + 1))
    if shuffle:
        ds = ds.shuffle(100_000, seed=seed)
    ds = ds.batch(batch_size)
    return ds.map(lambda window: (window[:, :-1], window[:, 1:])).prefetch(1)

In [40]:
# extra code – a simple example using to_dataset()
# There's just one sample in this dataset: the input represents "to b" and the
# output represents "o be"
list(to_dataset(text_vec_layer(["To be"])[0], length=4))

[(<tf.Tensor: shape=(1, 4), dtype=int64, numpy=array([[ 4,  5,  2, 23]])>,
  <tf.Tensor: shape=(1, 4), dtype=int64, numpy=array([[ 5,  2, 23,  3]])>)]

In [41]:
length = 100
tf.random.set_seed(42)
train_set = to_dataset(encoded[:1_000_000], length=length, shuffle=True,
                       seed=42)
valid_set = to_dataset(encoded[1_000_000:1_060_000], length=length)
test_set = to_dataset(encoded[1_060_000:], length=length)

In [44]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=n_tokens, output_dim=16),
    tf.keras.layers.GRU(128, return_sequences=True),
    tf.keras.layers.Dense(n_tokens, activation="softmax")
])
model.compile(loss="sparse_categorical_crossentropy",
              optimizer="nadam",
              metrics=["accuracy"])

model_ckpt = tf.keras.callbacks.ModelCheckpoint(
    "my_shakespeare_model",
    monitor="val_accuracy",
    save_best_only=True)

history = model.fit(train_set,
                    validation_data=valid_set,
                    epochs=1,
                    callbacks=[model_ckpt])

2022-09-03 15:43:56.142962: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:390] Filling up shuffle buffer (this may take a while): 68335 of 100000
2022-09-03 15:44:00.527162: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:415] Shuffle buffer filled.


  31247/Unknown - 1783s 57ms/step - loss: 1.4039 - accuracy: 0.5705

INFO:tensorflow:Assets written to: my_shakespeare_model/assets


INFO:tensorflow:Assets written to: my_shakespeare_model/assets


31247/31247 [==============================] - 1821s 58ms/step - loss: 1.4039 - accuracy: 0.5705 - val_loss: 1.6318 - val_accuracy: 0.5273
